### PR TITLE
Featured update

### PR DESCRIPTION
**Pull request by Dilyen**
kindly review my code for me!!!!!!!!!!!!!!!!!

### CODE REVIEW

**Review by YaaNuamah — APPROVED** [review]

**Review by YaaNuamah — APPROVED** [review]
Checked. All is good.

**Review by Dilyen — COMMENTED** [review]
will take note of the changes

**Review by Dilyen — COMMENTED** [review]
thanks

**Review by Dilyen — COMMENTED** [review]
okk

**Review by Dilyen — COMMENTED** [review]
Alright

**Review by Dilyen — COMMENTED** [review]
see all

**Comment by Dilyen** [comment]
checked all comments

**Pull request merged**
